### ISSUE TITLE
--ignore does not work for url variable like ?replytocom=12345

### ISSUE THREAD

**Issue by MichaelvanLohuizen** [spatie/mixed-content-scanner-cli#13]
While using mixed-content-scanner on a WordPress site it became apparent that all comment links were treated as separate posts. With x number of comments per post, scanning a site can become quite resource heavy.

WordPress comment links look like: **domain.tld/name-of-post/?replytocom=12345**

While it is possible to add **--ignore** and ignore page, tag, category, author and wp-content (for exclusion of direct image/file links) succesfully with:

`--ignore="\/tag\/" --ignore="\/page\/" --ignore="\/category\/" --ignore="\/author\/" --ignore="\/wp-content\/"`

I have not been able to exclude urls containing the variable **replytocom**, --ignore="replytocom" has no effect.

**mixed-content-scan** on which **mixed-content-scanner** is inspired does offer (through an ignore file) the option of ignoring urls containing replytocom by adding **\?replytocom\=** to the ignore file.

Possibly I'm overlooking something obvious but if not I think future users could benefit from including this option. Thank you for your time.

**Comment by brendt** [comment]
This has been fixed with 1.1.1: https://github.com/spatie/mixed-content-scanner-cli/releases/tag/1.1.1
