### ISSUE TITLE
Scan all pages listed in xml sitemap?

### ISSUE THREAD

**Issue by stefahn** [spatie/mixed-content-scanner-cli#17]
Thanks for your handy tool, like it very much.

Is there a way to scan all pages that are listed in a xml sitemap?
I tried ` php_cli mixed-content-scanner scan https://domain.de/page-sitemap.xml` but that only scans the xml file itself.

A workaround is to generate a html file out of the xml file, but maybe there is a faster way of doing it?

**Comment by freekmurze** [comment]
Thanks!

> A workaround is to generate a html file out of the xml file, but maybe there is a faster way of doing it?

There is currently no other way to do this.
