### ISSUE TITLE
php version?

### ISSUE THREAD

**Issue by adriancotter** [spatie/mixed-content-scanner-cli#8]
Thanks for this tool!

Does it only work with a certain version of PHP? 
Is it PHP 7 only? (I noticed that with another tool of yours laravel-translation-loader)

When I went to install with composer, I got the error
"Could not find package spatie/mixed-content-scanner-cli at any version matching your PHP version 5.6.19.0"

If so, I would just recommend noting that in the readme. Cheers.

**Comment by freekmurze** [comment]
Most of our stuff is indeed PHP 7 only.

You can view the required php version of any package in `composer.json`.
