### ISSUE TITLE
Not scanning subpages?

### ISSUE THREAD

**Issue by adriancotter** [spatie/mixed-content-scanner-cli#9]
Thanks for your answer re PHP yesterday. Got it working,

What might be some reason that the scan doesn't hit subpages? It seems to be working fine on one of my production sites (postcard coming soon!), but doesn't go beyond the homepage on a dev site (which is publicly available).

I don't have anything in the robots.txt file that would block it that I might know of, and I can't think of anything else off hand which would prevent it from spidering.

Thanks for any thoughts...

**Comment by adriancotter** [comment]
It does return a result for the initial page ("Found 1 page without mixed content")

**Comment by freekmurze** [comment]
Try to do a curl request to the page that is giving you troubles. Does it send back the correct html?

**Comment by adriancotter** [comment]
Yes, seems to be working fine.

**Comment by adriancotter** [comment]
Well I doublechecked by outputting the HTML in MixedContentExtractor and it turns out our firewall is blocking it. Which I should be able to get fixed.
